name: Enforce Community Health Files

on:
  workflow_dispatch: # adds a button so that it can run manually or it can be scheduled (below)
  schedule:
    - cron: '0 1 * * *'

jobs:
  check-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          echo "Starting repo health check..."

      - name: Run health check
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG_NAME: michelle-swissgrid-demo
        run: |
          REQUIRED_FILES=("README.md" "LICENSE" "CODE_OF_CONDUCT.md")

          page=1
          repos=()

          while :; do
            result=$(curl -s -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100&page=$page")

            names=$(echo "$result" | jq -r '.[].name')

            if [[ -z "$names" ]]; then
              break
            fi  

            repos+=($names)
            ((page++))
          done

          for repo in "${repos[@]}"; do
            echo "Checking repo: $repo"
            missing=0
            MISSING_FILES=$'\n'

            for file in "${REQUIRED_FILES[@]}"; do
              found=false

              for path in "$file" ".github/$file" "docs/$file"; do
                code=$(curl -s -o /dev/null -w "%{http_code}" \
                  -H "Authorization: token $GH_TOKEN" \
                  https://api.github.com/repos/$ORG_NAME/$repo/contents/$path)

                if [[ "$code" == "200" ]]; then
                  found=true
                  break
                fi
              done

              if [[ "$found" == "false" ]]; then
                echo "❌ Missing $file in $repo"
                missing=$((missing+1))
                MISSING_FILES+="- $file"$'\n'
              fi
            done

            archived=$(curl -s -H "Authorization: token $GH_TOKEN" \
              https://api.github.com/repos/$ORG_NAME/$repo | jq -r '.archived')

            if [[ "$missing" -gt 0 ]]; then
              if [[ "$archived" == "false" ]]; then
                echo "⚠️ Archiving $repo due to missing files..."
                gh api -X POST "repos/$ORG_NAME/$repo/issues" \
                  -f title="📁 Repository Archived Due to Missing Community Health Files" \
                  -f body="This repository has been archived because it is missing required community health files:"$MISSING_FILES$'\n'"Please add the missing files and contact the org maintainers to request unarchiving."
                curl -s -X PATCH \
                  -H "Authorization: token $GH_TOKEN" \
                  -H "Content-Type: application/json" \
                  -d '{"archived": true}' \
                  https://api.github.com/repos/$ORG_NAME/$repo
              else
                echo "📁 $repo is already archived."
              fi
            else
              echo "✅ $repo passed the check."
            fi
          done
